development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://szxxplcfezpenx:44bedf34c0619a539839e714d25f75003ef69c7d6ce45d7cae5834349b6c38de@ec2-184-73-167-43.compute-1.amazonaws.com:5432/d9e88hhqjmm2uc
  channel_prefix: summer_production
