# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Product.create(name: "The Big Cat", image_url:"b1.jpg", price:"1599", description: "Cat ipsum dolor sit amet, scamper, human is washing you why halp oh the horror flee scratch hiss bite, but when in doubt, wash sweet beast. Kitty power. Favor packaging over toy meowing chowing and wowing cough hairball on conveniently placed pants. Purrr purr littel cat, little cat purr purr stare at ceiling, and purr for no reason meowzer.")
Product.create(name: "Blackie", image_url:"b3.jpg", price:"499", description: "Lorizzle ipsum dolizzle daahng dawg amet, shiz adipiscing bow wow wow. Nullizzle sapizzle boom shackalack, aliquet volutpizzle, fizzle quizzle, gravida vel, fo shizzle. Ass you son of a bizzle tortizzle. Sed eros. Fusce izzle dolor brizzle break yo neck, yall tempizzle black. Maurizzle pellentesque bling bling izzle bling bling. Vestibulum in tortor. For sure fizzle rhoncizzle nisi. In dawg habitasse platea dictumst. For sure dapibizzle. Curabitur tellizzle go to hizzle, pretium eu, mattizzle that's the shizzle, its fo rizzle vitae, nunc. I saw beyonces tizzles and my pizzle went crizzle suscipit. Integer semper velit sizzle purizzle.")
Product.create(name: "Rocket Girl", image_url:"b6.jpg", price:"1499", description: "Tilford knockteberg hors delai campagnolo. Vaughters indurain vandenbroucke, meyrueis rouleur derby rouleur supplesse battoowoo greekgreek berendries, cavendish liege-bastogne-liege kaperij. Geraardsbergen geraardsbergen caravane bromont.")
Product.create(name: "Iron Pig", image_url:"b4.jpg", price:"399", description: "Meatloaf tri-tip chuck biltong, kevin drumstick bresaola pork capicola. Cow pig brisket corned beef tenderloin bresaola kevin bacon. Shoulder tenderloin strip steak boudin picanha. Spare ribs jerky t-bone ground round leberkas short ribs pork belly ham bacon corned beef cupim short loin. Chuck pastrami pork chop flank ball tip short loin. Jowl corned beef sirloin, swine pork chop ribeye short ribs picanha cupim frankfurter ball tip drumstick andouille ham. Bacon pork loin shoulder, venison porchetta short loin rump flank pancetta.")
Product.create(name: "Baby", image_url:"b5.jpg", price:"249", description: "Ga whoopsie gaga da gaa doo gaga doodoo laa. Gaagaa da doo laalaa gaagaa gaa dada huggle gaagaa. Caca laa da googoo da dada laa y. Doo gaagaa dada gaa ickle botty po.")
Product.create(name: "Venture", image_url:"b2.jpg", price:"1799", description: "Lorizzle ipsizzle dolor break yo neck, yall izzle, fizzle adipiscing elit. Nullizzle shizzlin dizzle velizzle, fo shizzle volutpizzle, yo ass, you son of a bizzle vizzle, break it down.")